// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCvJaOzYEXrDm67aZ_fYaBK8taAjxVHqU',
    appId: '1:342389399154:web:d48f4dd8be84251c6d6ceb',
    messagingSenderId: '342389399154',
    projectId: 'bookly-c4ce0',
    authDomain: 'bookly-c4ce0.firebaseapp.com',
    storageBucket: 'bookly-c4ce0.appspot.com',
    measurementId: 'G-9EJEQ18LYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6gVXh2GFmdtGAmm-Wolqg5oAurlRhmYo',
    appId: '1:342389399154:android:12091ef34f01b28a6d6ceb',
    messagingSenderId: '342389399154',
    projectId: 'bookly-c4ce0',
    storageBucket: 'bookly-c4ce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTefLotY1yE0J233gZ1dDbSyV1QduFCw',
    appId: '1:342389399154:ios:4ad58a56c2af3a146d6ceb',
    messagingSenderId: '342389399154',
    projectId: 'bookly-c4ce0',
    storageBucket: 'bookly-c4ce0.appspot.com',
    iosClientId: '342389399154-3a7j3lnbod17r57vkhnmi3pnng3snakq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmTefLotY1yE0J233gZ1dDbSyV1QduFCw',
    appId: '1:342389399154:ios:e44e7757b642d7856d6ceb',
    messagingSenderId: '342389399154',
    projectId: 'bookly-c4ce0',
    storageBucket: 'bookly-c4ce0.appspot.com',
    iosClientId: '342389399154-ltio54cf8vm8a8i9cjvkq4uj4fov8bef.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookly.RunnerTests',
  );
}
